# Generated by Django 4.2.25 on 2025-11-10 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('servings', models.DecimalField(decimal_places=1, max_digits=5)),
                ('total_calories', models.DecimalField(decimal_places=1, max_digits=8)),
            ],
        ),
    ]
