# Generated by Django 4.2.25 on 2025-11-11 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='total_calories',
        ),
    ]
